language: node_js
node_js: stable
cache:
  directories:
    - node_modules

script:
  - npm run lint

deploy:
  provider: npm
  email: goryakin@phystech.edu
  api_key: 
    secure: $npm_auth_token
  local_dir: build
  skip_cleanup: true